app:
  name: angular-spring-jwt

jwt:
  header: Authorization
  expires_in: 600 # 10 minutes
  secret: queenvictoria
  cookie: AUTH-TOKEN

server:
  port : 8081

spring:
  jpa:
    hibernate:
      # possible values: validate | update | create | create-drop
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost/feedbackboard
    username: FeedbackBoardUser
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    org.springframework.web: ERROR
    at.lolokraus: DEBUG
